Head:     master font-gnu-unifont 13.0.02 (#2032)
Merge:    origin/master font-gnu-unifont 13.0.02 (#2032)

Unstaged changes (1)
modified   Casks/font-ibm-plex.rb
@@ -1,114 +1,24 @@
-cask 'font-ibm-plex' do
-  version '4.0.2'
+cask 'font-ligalex-mono' do
+  version '4'
   sha256 '6615c5b5ecf5736a5ed29b7f99b780d3ae503e81962fe2259b30fdc322416d9d'
 
-  url "https://github.com/IBM/plex/releases/download/v#{version}/OpenType.zip"
-  appcast 'https://github.com/IBM/plex/releases.atom'
-  name 'IBM Plex'
-  homepage 'https://github.com/IBM/plex'
+  url "https://github.com/ToxicFrog/Ligaturizer/releases/download/v#{version}/LigaturizedFonts.zip"
+  name 'Ligalex Mono'
+  homepage 'https://github.com/ToxicFog/Ligaturizer'
 
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Bold.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-BoldItalic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-ExtraLightItalic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Italic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Light.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-LightItalic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Medium.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-MediumItalic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Regular.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-SemiBoldItalic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Text.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-TextItalic.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-Thin.otf'
-  font 'OpenType/IBM-Plex-Mono/IBMPlexMono-ThinItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Light.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Text.otf'
-  font 'OpenType/IBM-Plex-Sans-Arabic/IBMPlexSansArabic-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-BoldItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-ExtraLightItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Italic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Light.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-LightItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-MediumItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-SemiBoldItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Text.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-TextItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans-Condensed/IBMPlexSansCondensed-ThinItalic.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-Light.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-Text.otf'
-  font 'OpenType/IBM-Plex-Sans-Devanagari/IBMPlexSansDevanagari-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-Light.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-Text.otf'
-  font 'OpenType/IBM-Plex-Sans-Hebrew/IBMPlexSansHebrew-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-Light.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-Text.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai-Looped/IBMPlexSansThaiLooped-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-Light.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-Text.otf'
-  font 'OpenType/IBM-Plex-Sans-Thai/IBMPlexSansThai-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Bold.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-BoldItalic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-ExtraLightItalic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Italic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Light.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-LightItalic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Medium.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-MediumItalic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Regular.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-SemiBoldItalic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Text.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-TextItalic.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-Thin.otf'
-  font 'OpenType/IBM-Plex-Sans/IBMPlexSans-ThinItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Bold.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-BoldItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-ExtraLight.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-ExtraLightItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Italic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Light.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-LightItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Medium.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-MediumItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Regular.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-SemiBold.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-SemiBoldItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Text.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-TextItalic.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-Thin.otf'
-  font 'OpenType/IBM-Plex-Serif/IBMPlexSerif-ThinItalic.otf'
+  font 'LigalexMono-Thin.ttf'
+  font 'LigalexMono-LightItalic.ttf'
+  font 'LigalexMono-SemiBoldItalic.ttf'
+  font 'LigalexMono-BoldItalic.ttf'
+  font 'LigalexMono-SemiBold.ttf'
+  font 'LigalexMono-ExtraLight.ttf'
+  font 'LigalexMono-Text.ttf'
+  font 'LigalexMono-Medium.ttf'
+  font 'LigalexMono-MediumItalic.ttf'
+  font 'LigalexMono-ThinItalic.ttf'
+  font 'LigalexMono-Light.ttf'
+  font 'LigalexMono-Italic.ttf'
+  font 'LigalexMono-ExtraLightItalic.ttf'
+  font 'LigalexMono-TextItalic.ttf'
+  font 'LigalexMono-Bold.ttf'
 end

Recent commits
5c1d98b master origin/master font-gnu-unifont 13.0.02 (#2032)
f8551ce Updated font jetbrains mono to 1.0.6 (#2031)
a624c89 Update font-jf-open-huninn from 1.0 to 1.1 (#2026)
5565df2 Add font-ipamjmincho 006.01 (#2027)
1165eff Add font-gen{yo,ryu,wan}min, font-gen{yo,seki}gothic, font-gensenrounded v1.501 (#2028)
0bee4af Update font Work Sans to use master version (#2030)
ab9f2e7 Update font-cozette from 1.7.0 to 1.8.0 (#2025)
d71f242 Update font-sarasa-gothic from 0.12.4 to 0.12.5 (#2024)
9449d39 Update Roboto Condensed URL after Roboto was updated to v3 (#2022)
8443e40 WIP Add font-lilex 1.000 (#2013)

